-- Create Profiles table to store public user data
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email varchar(255) not null,
  nickname varchar(50),
  avatar_url varchar(255),
  manner_score float8 default 36.5,
  participation_score integer default 0,
  is_online boolean default false
);

-- Create Studies table
create table studies (
  id bigint generated by default as identity primary key,
  leader_id uuid references public.profiles not null,
  title varchar(100) not null,
  description text,
  enrollment_type varchar(20) not null default 'open', -- 'open' or 'approval'
  status varchar(20) not null default 'active', -- 'active' or 'ended'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Study Members table
create table study_members (
  study_id bigint references public.studies on delete cascade not null,
  user_id uuid references public.profiles on delete cascade not null,
  role varchar(20) not null default 'member', -- 'leader' or 'member'
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (study_id, user_id)
);

-- Create Messages table for the chat system
create table messages (
  id bigint generated by default as identity primary key,
  study_id bigint references public.studies on delete cascade not null,
  user_id uuid references public.profiles on delete cascade not null,
  content text,
  image_url varchar(255),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;
alter table studies enable row level security;
alter table study_members enable row level security;
alter table messages enable row level security;

-- RLS Policies for profiles
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile." on profiles for update using (auth.uid() = id);

-- RLS Policies for studies
create policy "Studies are viewable by everyone." on studies for select using (true);
create policy "Authenticated users can create studies." on studies for insert with check (auth.role() = 'authenticated');
create policy "Study leaders can update their own studies." on studies for update using (auth.uid() = leader_id);
create policy "Study leaders can delete their own studies." on studies for delete using (auth.uid() = leader_id);

-- RLS Policies for study_members
create policy "Study members can view the member list." on study_members for select using (
  exists (
    select 1 from study_members
    where study_members.study_id = study_id and study_members.user_id = auth.uid()
  )
);
create policy "Users can join studies." on study_members for insert with check (auth.role() = 'authenticated');
create policy "Study leaders can remove members." on study_members for delete using (
  exists (
    select 1 from studies
    where studies.id = study_members.study_id and studies.leader_id = auth.uid()
  )
);
create policy "Members can leave a study." on study_members for delete using (auth.uid() = user_id);

-- RLS Policies for messages
create policy "Study members can view messages." on messages for select using (
  exists (
    select 1 from study_members
    where study_members.study_id = messages.study_id and study_members.user_id = auth.uid()
  )
);
create policy "Study members can send messages." on messages for insert with check (
  exists (
    select 1 from study_members
    where study_members.study_id = messages.study_id and study_members.user_id = auth.uid()
  )
);


-- Function to create a new profile for a new user
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, nickname, avatar_url)
  values (new.id, new.email, NULL, new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function when a new user signs up
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Set up Storage for chat images
insert into storage.buckets (id, name, public)
values ('chat-images', 'chat-images', true);

create policy "Chat images are publicly accessible." on storage.objects for select using (bucket_id = 'chat-images');
create policy "Authenticated users can upload chat images." on storage.objects for insert with check (bucket_id = 'chat-images' and auth.role() = 'authenticated');

-- Create Attendance Logs table
create table attendance_logs (
  id bigint generated by default as identity primary key,
  study_id bigint references public.studies on delete cascade not null,
  user_id uuid references public.profiles on delete cascade not null,
  checked_in_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_manual_override boolean default false
);

-- RLS for attendance_logs
alter table attendance_logs enable row level security;
create policy "Members can view their own attendance." on attendance_logs for select using (auth.uid() = user_id);
create policy "Authenticated users can insert attendance." on attendance_logs for insert with check (auth.role() = 'authenticated');

-- RPC function to apply penalties
create or replace function apply_penalty(
    p_user_id uuid,
    p_manner_deduction float8,
    p_participation_deduction integer
)
returns void as $$
begin
  update public.profiles
  set
    manner_score = manner_score - p_manner_deduction,
    participation_score = participation_score - p_participation_deduction
  where id = p_user_id;
end;
$$ language plpgsql;

